models:
  - name: ESM1b
    path: ESM1b
    category: sequence
    color: "#B9DFF5"
    score_column: "esm1b_t33_650M_UR50S"
  - name: ESM1v
    path: ESM1v
    category: sequence
    color: "#5DA8D4"
    score_column: "Ensemble_ESM1v"
  - name: ESM1v_1
    path: ESM1v
    category: sequence
    color: "#5DA8D4"
    score_column: "esm1v_t33_650M_UR90S_1"
  - name: ESM1v_2
    path: ESM1v
    category: sequence
    color: "#5DA8D4"
    score_column: "esm1v_t33_650M_UR90S_2"
  - name: ESM1v_3
    path: ESM1v
    category: sequence
    color: "#5DA8D4"
    score_column: "esm1v_t33_650M_UR90S_3"
  - name: ESM1v_4
    path: ESM1v
    category: sequence
    color: "#5DA8D4"
    score_column: "esm1v_t33_650M_UR90S_4"
  - name: ESM1v_5
    path: ESM1v
    category: sequence
    color: "#5DA8D4"
    score_column: "esm1v_t33_650M_UR90S_5"
  - name: ESM-IF1
    path: ESM-IF1
    category: structure
    color: "#001EB3"
    score_column: "esmif1_ll"
  - name: ESM2
    path: ESM2
    category: sequence
    color: "#3ED3E1"
    variants:
      - name: 8M
        path: ESM2/8M
        score_column: "esm2_t6_8M_UR50D"
      - name: 35M
        path: ESM2/35M
        score_column: "esm2_t12_35M_UR50D"
      - name: 150M
        path: ESM2/150M
        score_column: "esm2_t30_150M_UR50D"
      - name: 650M
        path: ESM2/650M
        score_column: "esm2_t33_650M_UR50D"
      - name: 3B
        path: ESM2/3B
        score_column: "esm2_t36_3B_UR50D"
  - name: EVE
    path: EVE
    category: MSA
    color: "#009E73"
    score_column: "evol_indices_seed_42"
  - name: VESPA
    path: VESPA
    category: sequence
    color: "#A52A2A"
    score_column: "VESPA"
  - name: EVmutation
    path: EVmutation
    category: MSA
    color: "#00cc33"
    score_column: "prediction_epistatic"
  - name: Tranception
    path: Tranception
    category: MSA
    color: "#e0863d"
    variants:
      - name: S
        path: Tranception/Tranception_S
        score_column: "avg_score"
      - name: M
        path: Tranception/Tranception_M
        score_column: "avg_score"
      - name: L
        path: Tranception/Tranception_L
        score_column: "avg_score"
  - name: TranceptionNoRet
    path: Tranception_no_retrieval
    category: sequence
    color: "#F7A96A"
    variants:
      - name: S
        path: Tranception_no_retrieval/Tranception_S
        score_column: "avg_score"
      - name: M
        path: Tranception_no_retrieval/Tranception_M
        score_column: "avg_score"
      - name: L
        path: Tranception_no_retrieval/Tranception_L
        score_column: "avg_score"
  - name: TranceptEVE
    path: TranceptEVE
    category: MSA
    color: "#750000"
    variants:
      - name: S
        path: TranceptEVE/TranceptEVE_S
        score_column: "avg_score"
      - name: M
        path: TranceptEVE/TranceptEVE_M
        score_column: "avg_score"
      - name: L
        path: TranceptEVE/TranceptEVE_L
        score_column: "avg_score"
  - name: Progen2
    path: Progen2
    category: sequence
    color: "#CC79A7"
    variants:
      - name: small
        path: Progen2/small
        score_column: "Progen2_score"
      - name: medium
        path: Progen2/medium
        score_column: "Progen2_score"
      - name: base
        path: Progen2/base
        score_column: "Progen2_score"
      - name: large
        path: Progen2/large
        score_column: "Progen2_score"
  - name: RITA
    path: RITA
    category: sequence
    color: "#d5c711"
    variants:
      - name: small
        path: RITA/small
        score_column: "RITA_score"
      - name: medium
        path: RITA/medium
        score_column: "RITA_score"
      - name: large
        path: RITA/large
        score_column: "RITA_score"
      - name: xlarge
        path: RITA/xlarge
        score_column: "RITA_score"
  - name: ProteinMPNN
    path: ProteinMPNN
    category: structure
    color: "darkgray"
    score_column: "pmpnn_ll"
  - name: ProtGPT2
    path: ProtGPT2
    category: sequence
    color: "darkgreen"
    score_column: "ProtGPT2_score"
  - name: UniRep
    path: UniRep
    category: sequence
    color: "#8b1e65"
    score_column: "Unirep_score"
  - name: eUniRep
    path: UniRep_evotuned
    category: MSA
    color: "#cc70e6"
    score_column: "Unirep_score"
  - name: CARP
    path: CARP
    category: sequence
    color: "#f77189"
    variants:
      - name: 600K
        path: CARP/600K
        score_column: "carp_600k_score"
      - name: 38M
        path: CARP/38M
        score_column: "carp_38M_score"
      - name: 76M
        path: CARP/76M
        score_column: "carp_76M_score"
      - name: 640M
        path: CARP/640M
        score_column: "carp_640M_score"
  - name: ESCOTT
    path: ESCOTT
    category: all
    color: "#97a431"
    score_column: "ESCOTT_score"
  - name: GEMME
    path: GEMME
    category: MSA
    color: "#50b131"
    score_column: "GEMME_score"
  - name: MIF
    path: MIF
    category: structure
    color: "#C2A04D"
    score_column: "mif_score"
  - name: MIFST
    path: MIFST
    category: structure
    color: "#8C6E1C"
    score_column: "mifst_score"
  - name: MSATransformer
    path: MSA_Transformer
    category: MSA
    color: "#4169E1"
    score_column: "esm_msa1b_t12_100M_UR50S_ensemble"
  - name: MULAN
    path: MULAN
    category: structure
    color: "#FF1493"
    variants:
      - name: small
        path: MULAN/MULAN_small
        score_column: "MULAN_score"
  - name: ProSST
    path: ProSST
    category: structure
    color: "#3ba3ec"
    variants:
      - name: "20"
        path: ProSST/20
        score_column: "ProSST-20"
      - name: "128"
        path: ProSST/128
        score_column: "ProSST-128"
      - name: "512"
        path: ProSST/512
        score_column: "ProSST-512"
      - name: "1024"
        path: ProSST/1024
        score_column: "ProSST-1024"
      - name: "2048"
        path: ProSST/2048
        score_column: "ProSST-2048"
      - name: "4096"
        path: ProSST/4096
        score_column: "ProSST-4096"
  - name: ProtSSN
    path: ProtSSN
    category: structure
    color: "#6A0DAD"
    score_column: "ProtSSN_ensemble"
  - name: RSALOR
    path: RSALOR
    category: all
    color: "#DE3163"
    score_column: "RSALOR"
  - name: SaProt
    path: SaProt
    category: structure
    color: "#D147D1"
    variants:
      - name: 650M_AF2
        path: SaProt/SaProt_650M_AF2
        score_column: "SaProt_score"
  - name: VenusREM
    path: VenusREM
    category: all
    color: "#2F8475"
    variants:
      - name: "20"
        path: VenusREM/20
        score_column: "VenusREM"
      - name: "128"
        path: VenusREM/128
        score_column: "VenusREM"
      - name: "512"
        path: VenusREM/512
        score_column: "VenusREM"
      - name: "1024"
        path: VenusREM/1024
        score_column: "VenusREM"
      - name: "2048"
        path: VenusREM/2048
        score_column: "VenusREM"
      - name: "4096"
        path: VenusREM/4096
        score_column: "VenusREM"


      
